
declare module breeze.config {
    class MetadataHelper {
        addDataService: any;
        addTypeNameAsResource: any;
        addTypeToStore: any;
        convertValidators: any;
        findEntityKey: any;
        inferDefaultResourceName: any;
        inferValidators: any;
        patch: any;
        pluralize: any;
        replaceDataPropertyAliases: any;
        replaceNavPropertyAliases: any;
        setDefaultAutoGeneratedKeyType: any;
        setDefaultNamespace: any;
        _hasOwnProperty: any;
        _isArray: any
    }

}