'use strict';
module App {
    export class MetadataHelper {
        public static FillMetadataStore(store) {

            // Metadata-Helper instance configured with default namespace and key generator for this model
            var helper = new breeze.config.MetadataHelper('GreyTide.Models', breeze.AutoGeneratedKeyType.Identity);
            // DataTypes
            var DT = breeze.DataType;
            var BOOL = DT.Boolean;
            var DATE = DT.DateTime;
            var ID = DT.Int32;
            var GUID = DT.Guid;
            var STRING = DT.String;

            // type order is irrelevant
            addModel();
            addModelState();
            addFromState();
            addStateCollection();
            addState();
            // addType - make it easy to add the type to the store using the helper
            function addType(type) {
                helper.addTypeToStore(store, type);
            };

            function addModel() {
                addType({
                    name: 'Model',
                    dataProperties: {
                        UserToken: { type: GUID, required: true },
                        Id: { type: GUID, required: true },
                        Name: { type: STRING, required: true },
                        CurrentState: { type: STRING },
                        CurrentDate: { type: DATE },
                        Faction: { type: STRING },
                        Points: { type: ID }, 
                        ParentId: { type: GUID }
                    },
                    navigationProperties :{ 
                        Items: { type: 'Model', hasMany: true },
                        States: { type: 'ModelState', hasMany: true },
                        Parent: { type: 'Model', hasMany: false }
                    }

                });
            };
            function addModelState() {
                addType({
                    name: 'ModelState',
                    isComplexType: true,
                    dataProperties: {
                        Name: { type: STRING, required: true },
                        Date: { type: DATE, required: true }
                    }
                });
            };
            function addFromState() {
                addType({
                    name: 'FromState',
                    isComplexType: true,
                    dataProperties: {
                        Name: { type: STRING, required: true }
                    }
                });
            };
            function addState() {
                addType({
                    name: 'State',
                    isComplexType: true,
                    dataProperties: {
                        Order: { type: ID, required: true },
                        Name: { type: STRING, required: true },
                        To: { type: STRING, required: true }
                    },
                    navigationProperties: {
                        From: { type: 'FromState', hasMany: true }
                    }
                });
            };
            function addStateCollection() {
                addType({
                    name: 'StateCollection',
                    dataProperties: {
                        UserToken: { type: GUID, required: true },
                        Id: { type: GUID, required: true },
                        Name: { type: STRING, required: true }
                    }, navigationProperties: {
                        Events: { type: 'State', hasMany: true }
                    }
                });
            };
        }
    }
} 